[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --force"]

[phases.build]
# Las variables de entorno se establecerán desde Railway
cmds = ["npm run build"]

[start]
cmd = "npx serve -s build -l 3000"